language: bash
services: docker

env:
  - VERSION=18.09
  - VERSION=18.06

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="docker:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - travis_retry docker build -t "$image-dind" dind
  - ~/official-images/test/run.sh "$image-dind"
  - travis_retry docker build -t "$image-git" git
  - ~/official-images/test/run.sh "$image-git"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
